### PR TITLE
Adding option 'reuse address' to allow more than one server run on same port and address

### PR DESCRIPTION
**Pull request by paulobrizolara**
When using coap to listen multicast messages (or maybe in other scenarios) may be desirable to allow more than one smcp server to run on same machine and same port.

To allow that, i had added a function 'smcp_plat_set_reuse_address' to smcp_plat and implemented it on smcp-plat-bsd (i had not implemented on other platforms).

If reuse address is set to true, then the socket option SO_REUSEADDR is set to true when creating the socket (in  smcp_plat_bind_to_sockaddr).

### CODE REVIEW

**Comment by darconeous** [comment]
This is a tricky, since SMCP will always respond to confirmable multicast messages (as required). This will lead to strange and unpredictable behavior for unicast `GET` requests (and responses to other messages, too), so I'm not sure if enabling this is something we would want to support or encourage.

Why do you need to have more than one instance on a machine? There may be a better way to accomplish what you are trying to do.

**Comment by paulobrizolara** [comment]
Well, in long terms, i am trying to enable discovery of services between devices and between applications.
That way, two (or more) applications could listen to multicast requests to announce their services independently.
However, i am still researching how to do that.

I know that can be problems if two applications use that for receive unicast requests.
In my case, i intend to use it only to receive multicast messages.

If you think that this option should not be part of the library, maybe i could decouple the socket creation from the binding process. So, i could set the option manually after the socket creation and before the binding. Currently this is not possible, because both are done on same function (smcp_plat_bind_to_sockaddr) and the socket is destroyed if the bind fails.

What do you think?

**Comment by darconeous** [comment]
I'm all for keeping things as flexible as possible. To the extent that there is something you want to do that is somewhat reasonable, my philosophy is that the library shouldn't necessarily prevent you from doing that—and I think this case might qualify. I'd just rather not add the capability explicitly. I'm sure we can figure something out.

Regarding your overall architecture, D-Bus support was one of the things I was considering adding to `smcpd`, along with a D-Bus IPC protocol for adding modifying and removing resources from other processes. It may even make sense to implement some sort of dynamic reverse-proxy. This would allow any application to add resources to what would appear to be a single CoAP instance on a single port.

Thoughts?

**Comment by paulobrizolara** [comment]
About this pull-request, i think you can close/reject it.
I may submit another one that moves the socket creation to 'smcp_plat_init', if you do not mind. 
That way i could still play with 'reuse_address', but that will stay outside of library.

Anyway, i think that keep more than one coap instance (on same port) will not work rightly due to message duplication detection (that uses the source address as base).

So, i probably will use some kind of IPC (really thanks for the suggestion). 
I've not used D-Bus yet. But it looks very nice. I will take a better look on it.
However i am concerned about portability. 
I am planning to use this project on Android, for example.
I don't know how much portable it is.

**Comment by darconeous** [comment]
D-Bus is widely used on Linux platforms, including Android. However, on Android I believe you can only access it via the C API.

**Pull request closed without merging**
